### ISSUE TITLE
There are several bugs in code.

### ISSUE THREAD

**Issue by sookienlane** [AdeDZY/DeepCT#3]
1. Line 63-65: do_train and do_lower_case
2. miss max_seq_len
3. miss use_all_layers
4. no "TREC19MarcoDocProcessor"

**Comment by AdeDZY** [comment]
Thank you very much for pointing out the bugs! I accidentally deleted a few lines of code. I have recovered those lines. I've also removed the unused "TREC19MarcoDocProcessor".

https://github.com/AdeDZY/DeepCT/blob/6897f97599ee7cf35e9241c6fc224dca23e7d696/run_deepct.py#L63
