### ISSUE TITLE
运行环境的说明能给一下嘛

### ISSUE THREAD

**Issue by lomessa** [AdeDZY/DeepCT#5]

**Comment by AdeDZY** [comment]
Python 3
Tensorflow 1.15.0

Run time: a few hours on 4 GPU

Does the above information answer your question?

**Comment by lomessa** [comment]
> Python 3
> Tensorflow 1.15.0
> 
> Run time: a few hours on 4 GPU
> 
> Does the above information answer your question?
almost, thx!

**Comment by AdeDZY** [comment]
Let me know if you have any further questions :)
