### ISSUE TITLE
DeepCT-query instructions

### ISSUE THREAD

**Issue by joy-ko** [AdeDZY/DeepCT#7]
Thanks for your contribution and sharing.

It is interesting and the instructions are so clear to try out.
However, I want to ask you more instructions about DeepCT-query. 

Especially, I want to know how to run "QueryProcessor" in "run_deepct.py"
I tried several times but fail to run and get the result....

Thanks again for sharing.

**Comment by lzhenboy** [comment]
Have you solved this problem?
